### ISSUE TITLE
Bug: Reflection failed after (minor)Update -- Typo3 10.4.23 and 10.4.24

### ISSUE THREAD

**Issue by t3brinne** [joppnet/jn_phpcontentelement#11]
Hello,

I updated yesterday from 10.4.21 on 10.4.23 and got this error on all pages containing a phpcontent-element.
Error displayed since this update is: 
```
Oops, an error occurred!
Class Joppnet\JnPhpcontentelement\Controller\Joppnet\JnPhpcontentelement\Controller\JnPhpContentControllerController does not exist. Reflection failed.
More information regarding this error might be available [online](https://typo3.org/go/exception/CMS/1278450972).
```

Update today on 10.4.24 and (re)run 'composer req joppnet/jn_phpcontentelement' (Version 1.1.9 doesn't fix it spontaneously.
I didn't find a hint in the online information linked above. Any Ideas?

**Comment by oliverschloebe** [comment]
Fixed in https://github.com/joppnet/jn_phpcontentelement/releases/tag/1.2.0

Thanks for the heads-up!

**Comment by t3brinne** [comment]
Thanks, but it still doesn't work for me  :-/

Maybe the exception output is usefull -- is there a good way to post this html-code here?

**Comment by oliverschloebe** [comment]
> Thanks, but it still doesn't work for me :-/

Have you cleared all caches after updating the extensions?

> Maybe the exception output is usefull -- is there a good way to post this html-code here?

Please post the exception here: https://pastebin.com/

**Comment by t3brinne** [comment]
Here the exception as text and below as html: https://pastebin.com/0QCHhWn5

**Comment by oliverschloebe** [comment]
> Here the exception as text and below as html: https://pastebin.com/0QCHhWn5

May you please try running `composer dumpautoload`? Just to be sure.

You're running TYPO3 10.4.24 in Composer mode, right?

**Comment by t3brinne** [comment]
Yes, TYPO3 10.4. here is running in composer mode. We use a GitLab CI to build the instance and deploy it automatically on the previewserver and manually triggert to the deploymentserver. On this way everything is new downloaded/generated..

I tried "composer dump-autoload" on my development instance successfully with no error. 

But in the gitlab-ci output of preview and deploment I became this error: 

--8<---
```
> Class Joppnet\JnPhpcontentelement\Controller\JnPhpContentController located in ./web/typo3conf/ext/jn_phpcontentelement/Classes/Controller/JnPhpcontentController.php does not comply with psr-4 autoloading standard. Skipping.
> Class Joppnet\JnPhpcontentelement\Controller\JnPhpContentController located in ./web/typo3conf/ext/jn_phpcontentelement/Classes/Controller/JnPhpcontentController.php does not comply with psr-4 autoloading standard. Skipping.
```
--->8---

Which syntax is the right one? JnPhp**C**ontentController or JnPhp**c**ontentController
Is the syntax of `class JnPhpContentController` in the file JnPhpcontentController.php right?

thx for your help

**Comment by oliverschloebe** [comment]
Hi @t3brinne, may you please try to replace the `JnPhpcontentController.php` file's contents with this https://pastebin.com/fqv1MChi followed by running `composer dump-autoload` and see if that fixes the issue?

Thank you!

**Comment by t3brinne** [comment]
Dear Oliver, 
I just integrated in gitlab-ci in the surf process at the right point (where the composer exists) the `composer dump-autoload` command twice and now everything works fine. 
Sorry for the confusion on this topic and your help. 
Thanks a lot!
